inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/migrate/2016*'
    - 'db/migrate/2017*'

LineLength:
  Description: 'Limit lines to 200 characters.'
  Max: 200
  Enabled: true

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 15
  Exclude:
    - 'lib/generators/namespace/namespace_generator.rb'
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'db/**/*.rb'
  Enabled: true

Metrics/ClassLength:
  CountComments: false
  Max: 100
  Exclude:
    - 'lib/generators/namespace/namespace_generator.rb'
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - 'lib/generators/namespace/namespace_generator.rb'
  Enabled: true

Metrics/MethodLength:
  CountComments: false
  Max: 10
  Exclude:
    - 'lib/generators/namespace/namespace_generator.rb'
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# By default, the rails cops are not run. Override in project or home
# directory .rubocop.yml files, or by giving the -R/--rails option.
Rails:
  Enabled: true

Rails/Output:
  Enabled: true
  Exclude:
    - 'db/seeds.rb'
